export const fakeGamesData: any[] = [
    {
        name: 'Split Fiction EA App Key (PC) GLOBAL',
        price: 49.99,
        discount: 0.18,
        whishlisted: 5999,
        app: 'EA App',
        region: 'GLOBAL',
        cover: '/temp/fifa.jpg',
    },
    {
        name: 'Dragon Age: Dreadwolf EA App Key (PC) GLOBAL',
        price: 69.99,
        discount: 0.22,
        whishlisted: 8421,
        app: 'EA App',
        region: 'GLOBAL',
        cover: '/temp/rdr2.jpg',
    },
    {
        name: 'FIFA 25 EA App Key (PC) GLOBAL',
        price: 79.99,
        discount: 0.15,
        whishlisted: 15432,
        app: 'EA App',
        region: 'GLOBAL',
        cover: '/temp/fifa.jpg',
    },
    {
        name: 'Need for Speed: Unbound EA App Key (PC) GLOBAL',
        price: 59.99,
        discount: 0.35,
        whishlisted: 11204,
        app: 'EA App',
        region: 'GLOBAL',
        cover: '/temp/fifa.jpg',
    },
    {
        name: 'Star Wars Jedi: Survivor EA App Key (PC) GLOBAL',
        price: 69.99,
        discount: 0.4,
        whishlisted: 18976,
        app: 'EA App',
        region: 'GLOBAL',
        cover: '/temp/rdr2.jpg',
    },
];